name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn

      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn run check
      - run: yarn run prettier --check .
